language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.cache/bower"
    - "$HOME/.npm"

env:
  global:
    - NEXUS_USERNAME=travis
    - secure: nUO6i7ZkFW+cKNspEbOr5sj4CsY6AKfBGT/pDlPbdXOXjH+55MJY3cSAfC8jgDeIyJ6qMJuWiGf1Elg8Xnuicu5RsLKk3URUKn3peydJ/KwJe8XRdE6RYpKiMSp57PyQwHrbcGeyTEReHtThwu/v29xT29K/QRcxeDyyibSnj6M=

before_install:
  - npm install -g bower

script:
  - mvn clean test deploy --settings travis-maven-settings.xml
